# Generated by Django 5.1 on 2024-11-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_election_position_candidate_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='end_time',
        ),
    ]
